import os

from granian import Granian
from granian.http import HTTP2Settings
from granian.log import LogLevels
from granian.constants import (
    Interfaces,
    RuntimeModes,
    Loops,
    TaskImpl,
    HTTPModes,
    SSLProtocols,
)


if __name__ == "__main__":
    Granian(
        target="src.main:Main",
        address="0.0.0.0",
        port=8000,
        interface=Interfaces.RSGI,
        workers=os.cpu_count() or 1,
        blocking_threads=None,
        runtime_threads=1,
        runtime_mode=RuntimeModes.mt,
        loop=Loops.uvloop,
        task_impl=TaskImpl.asyncio,
        http=HTTPModes.http2,
        websockets=False,
        backlog=8 * 1024,
        backpressure=16 * 1024,
        http1_settings=None,
        http2_settings=HTTP2Settings(
            adaptive_window=True,
            initial_connection_window_size=2 * 1024 * 1024,
            initial_stream_window_size=2 * 1024 * 1024,
            keep_alive_interval=None,
            keep_alive_timeout=20,
            max_concurrent_streams=2 * 1024,
            max_frame_size=1024 * 32,
            max_headers_size=16 * 1024 * 1024,
            max_send_buffer_size=1024 * 400,
        ),
        log_enabled=True,
        log_level=LogLevels.info,
        log_dictconfig=None,
        log_access=False,
        log_access_format=None,
        ssl_cert=None,
        ssl_key=None,
        ssl_key_password=None,
        ssl_protocol_min=SSLProtocols.tls13,
        ssl_ca=None,
        ssl_crl=None,
        ssl_client_verify=False,
        url_path_prefix=None,
        respawn_failed_workers=True,
        respawn_interval=1.0,
        rss_sample_interval=30,
        rss_samples=1,
        workers_lifetime=None,
        workers_max_rss=None,
        workers_kill_timeout=None,
        factory=False,
        working_dir=None,
        env_files=None,
        static_path_route=None,
        static_path_mount=None,
        static_path_dir_to_file=None,
        static_path_expires=86400,
        metrics_enabled=False,
        metrics_scrape_interval=15,
        metrics_address="127.0.0.1",
        metrics_port=9090,
        reload=False,
        reload_paths=None,
        reload_ignore_dirs=None,
        reload_ignore_patterns=None,
        reload_ignore_paths=None,
        reload_filter=None,
        reload_tick=50,
        reload_ignore_worker_failure=False,
        process_name=None,
        pid_file=None,
    ).serve()
